### ISSUE TITLE
 pip-21.3 breaks pip-licenses

### ISSUE THREAD

**Issue by stishkin** [raimon49/pip-licenses#113]
/mnt/user$ pip-licenses -uf json
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/piplicenses.py", line 42, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/home/user/.local/lib/python3.8/site-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pip-licenses", line 5, in <module>
    from piplicenses import main
  File "/home/user/.local/lib/python3.8/site-packages/piplicenses.py", line 44, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/home/user/.local/lib/python3.8/site-packages/pip/__init__.py)
```

**Comment by SlavaSkvortsov** [comment]
If someone still wants to have the latest pip version you can use a fork while my PR is still on the review - `git+git://github.com/adjust/pip-licenses.git@v-3.5.3`
