### ISSUE TITLE
pip-licenses broken in python 3.11

### ISSUE THREAD

**Issue by b-kamphorst** [raimon49/pip-licenses#128]
`pip-licenses` is broken in python 3.11 for `pip>=22.1`.

The issue is roughly the same as in #113. Log:

```bash
$ pip-licenses
Traceback (most recent call last):
  File "/builds/gitlab/.../.venv/bin/pip-licenses", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/builds/gitlab/.../stubs/.venv/lib/python3.11/site-packages/piplicenses.py", line 900, in main
    output_string = create_output_string(args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/gitlab/.../stubs/.venv/lib/python3.11/site-packages/piplicenses.py", line 558, in create_output_string
    table = create_licenses_table(args, output_fields)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/gitlab/.../stubs/.venv/lib/python3.11/site-packages/piplicenses.py", line 303, in create_licenses_table
    for pkg in get_packages(args):
  File "/builds/gitlab/.../stubs/.venv/lib/python3.11/site-packages/piplicenses.py", line 2[54](...), in get_packages
    pkg_name = pkg.project_name
               ^^^^^^^^^^^^^^^^
AttributeError: 'PathDistribution' object has no attribute 'project_name'
```

**Comment by nejch** [comment]
@raimon49 I just opened this issue and your comment popped up a few seconds after :)

I installed the rc1 and this works for me on 3.11.

**Comment by raimon49** [comment]
RC2 is now available following bug reports and patches. #132 

```bash
pip install 'pip-licenses==4.0.0rc2'
```

We continue to welcome feedback.

**Comment by raimon49** [comment]
pip-licenses 4.0.0 has been officially released. Thank you all for your contributions.
https://pypi.org/project/pip-licenses/4.0.0/
