### ISSUE TITLE
Docker workflow is broken for packages that require compiling source distributions of C code

### ISSUE THREAD

**Issue by jameslamb** [raimon49/pip-licenses#28]
Today I ran this:

```
echo "pandas" > docker/requirements.txt
docker build -t myapp-licenses .
```

This resulted in a long stacktrace ending in the following:

```
        cmd_obj.run()
      File "/tmp/easy_install-egl5coo_/numpy-1.16.2/numpy/distutils/command/build_src.py", line 148, in run
      File "/tmp/easy_install-egl5coo_/numpy-1.16.2/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-egl5coo_/numpy-1.16.2/numpy/distutils/command/build_src.py", line 292, in build_library_sources
      File "/tmp/easy_install-egl5coo_/numpy-1.16.2/numpy/distutils/command/build_src.py", line 375, in generate_sources
      File "numpy/core/setup.py", line 667, in get_mathlib_info
        }
    RuntimeError: Broken toolchain: cannot link a simple C program
```

<details><summary>Full log</summary>
```
Sending build context to Docker daemon  260.6kB
Step 1/9 : FROM python:3.7.2-alpine
 ---> bb1ccaa5880c
Step 2/9 : LABEL maintainer="raimon <raimon49@hotmail.com>"
 ---> Using cache
 ---> 3cdaa5189f9b
Step 3/9 : ARG APPDIR=/opt/piplicenses
 ---> Using cache
 ---> ed8dba54bf41
Step 4/9 : WORKDIR ${APPDIR}
 ---> Using cache
 ---> 20e7835f3c04
Step 5/9 : COPY ./docker/requirements.txt ${APPDIR}
 ---> Using cache
 ---> c9cb8a93ad11
Step 6/9 : RUN python3 -m venv ${APPDIR}/myapp         && source ${APPDIR}/myapp/bin/activate
 ---> Using cache
 ---> 6d95570cbb70
Step 7/9 : RUN pip3 install -U pip         && pip3 install -r ${APPDIR}/requirements.txt         && pip3 install -U pip-licenses
 ---> Running in 54535904b617
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.0.3)
Collecting pandas (from -r /opt/piplicenses/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b2/4c/b6f966ac91c5670ba4ef0b0b5613b5379e3c7abdfad4e7b89a87d73bae13/pandas-0.24.2.tar.gz (11.8MB)
    Complete output from command python setup.py egg_info:
    /bin/sh: svnversion: not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    Running from numpy source directory.
    /tmp/easy_install-warv5lo9/numpy-1.16.2/setup.py:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/system_info.py:638: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/system_info.py:638: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    /tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/system_info.py:638: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    /tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/system_info.py:638: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/system_info.py:638: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    /usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/setup.py", line 415, in <module>

      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/setup.py", line 407, in setup_package
        cmdclass['cython'] = CythonCommand
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/core.py", line 171, in setup
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 148, in run
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 292, in build_library_sources
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 375, in generate_sources
      File "numpy/core/setup.py", line 667, in get_mathlib_info
        }
    RuntimeError: Broken toolchain: cannot link a simple C program

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vi1uiug3/pandas/setup.py", line 746, in <module>
        **setuptools_kwargs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/setup.py", line 415, in <module>

      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/setup.py", line 407, in setup_package
        cmdclass['cython'] = CythonCommand
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/core.py", line 171, in setup
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 148, in run
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 292, in build_library_sources
      File "/tmp/easy_install-warv5lo9/numpy-1.16.2/numpy/distutils/command/build_src.py", line 375, in generate_sources
      File "numpy/core/setup.py", line 667, in get_mathlib_info
        }
    RuntimeError: Broken toolchain: cannot link a simple C program

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vi1uiug3/pandas/
The command '/bin/sh -c pip3 install -U pip         && pip3 install -r ${APPDIR}/requirements.txt         && pip3 install -U pip-licenses' returned a non-zero code: 1
```
</details>

I got similar issues with other packages that include source distros of C/C++ which need to be compiled on install. For example

```
echo "xgboost" > docker/requirements.txt
docker build -t myapp-licenses .
```

**Comment by raimon49** [comment]
Thank you for the report.

I chose `python: 3.7.2-alpine` because I wanted to make the Docker image generated smaller.

This Docker environment is not ready to build a package that contains a C extension like pandas. I added this note to the README.

I may be able to accept Pull Requests to add alpine packages like `build-base`, `gcc` and others.

**Comment by raimon49** [comment]
Applying this patch will eliminate the error.

```diff
diff --git a/Dockerfile b/Dockerfile
index 039afee..6b04f0c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,6 +7,8 @@ WORKDIR ${APPDIR}

 COPY ./docker/requirements.txt ${APPDIR}

+RUN set -ex && apk add --no-cache --update --virtual .py-deps \
+        build-base
 RUN python3 -m venv ${APPDIR}/myapp \
         && source ${APPDIR}/myapp/bin/activate
```

However, the size of the generated Docker image has increased from 107MB to 269MB.

I want time to think about pros and cons.

**Comment by jameslamb** [comment]
Yep makes sense! I think image size shouldn't matter too much for this use case, since you're building a temporary isolated workspace, not an image that will become a deployed artifact.

Either way, totally up to you! It was pretty easy to use `pip-licenses` in Mac and various Linux distros based on the docs, so it's not like it's blocking me from using it.

**Comment by raimon49** [comment]
OK, I add this patch to the README and close the issue. Thank you for your opinion.
